spring.application.name=Product_Application_Server

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ProductSystem?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Taipei
spring.datasource.username=psm
spring.datasource.password=StrongPassword123!

# JWT Secret Key (?? 32 ??????????????)
jwt.secret=jG7$9bK!xQf8uW2@zR4tL#pD6vH1sM0yF!aCq3N^eXo

# JWT ???? (??)
jwt.expiration=3600000
